10 error component
luanlabs/wagent-interface pull request #14
Opened 2024-07-01 12:16 UTC by dousdogukan

### Description

implement CErrorCard

### Checklist

- [ ] Tested changes locally.
- [ ] Ensured code follows project standards.
- [ ] Updated documentation.
- [ ] Added necessary tests.

### Additional Notes

for #10

2024-07-04 06:03 UTC, ceydae commented
@ruveyda-kisla What's your thoughts about this?

2024-07-06 21:07 UTC, ruveyda-kisla requested changes

2024-07-06 21:07 UTC, ruveyda-kisla commented on src/assets/Close.tsx
import all Icon components you created to `index.tsx` in `src/assets`

2024-07-12 14:10 UTC, ceydae requested changes

2024-07-12 14:10 UTC, ceydae commented on src/components/CErrorCard/index.tsx
> +import ErrorIcon from '@/assets/ErrorIcon';
move below the package imports

2024-07-15 11:02 UTC, ceydae approved these changes

2024-07-16 12:42 UTC, ceydae requested changes

2024-07-16 12:42 UTC, ceydae commented on src/components/CPageCard/index.tsx
> +  error?: ErrorType | null;
remove `| null`

2024-07-18 22:09 UTC, ruveyda-kisla commented on src/components/CPageCard/index.tsx
> +      >
This causes CModal to not work as it should

2024-07-19 11:03 UTC, merged