21 loading modal component
luanlabs/wagent-interface pull request #22
Opened 2024-07-13 18:52 UTC by dousdogukan

### Description

implement CLoadingModal component

### Checklist

- [ ] Tested changes locally.
- [ ] Ensured code follows project standards.
- [ ] Updated documentation.
- [ ] Added necessary tests.

### Additional Notes

for #21

2024-07-14 12:35 UTC, ceydae requested changes

2024-07-14 12:35 UTC, ceydae commented on src/assets/Loading.tsx
> +        attributeName="transform"
fix props

2024-07-14 21:52 UTC, ruveyda-kisla approved these changes

2024-07-15 11:03 UTC, ceydae approved these changes

2024-07-15 14:15 UTC, merged