fix select token responsive
luanlabs/wagent-interface pull request #36
Opened 2024-07-29 18:37 UTC by dousdogukan

### Description

Removing the token selection restriction and fixing the responsive issues of Select in addProduct and editProduct.

### Checklist

- [ ] Tested changes locally.
- [ ] Ensured code follows project standards.
- [ ] Updated documentation.
- [ ] Added necessary tests.

### Additional Notes

for #34

2024-08-10 23:54 UTC, ceydae requested changes

2024-08-10 23:54 UTC, ceydae commented on src/components/CSelect/index.tsx
> +  initialEditProductSelectedLength?: number;
explain this to me

2024-08-25 19:43 UTC, ruveyda-kisla commented on src/components/CSelect/index.tsx
> +  initialEditProductSelectedLength?: number;
@dousdogukan

2024-08-30 11:54 UTC, ceydae requested changes

2024-08-30 11:54 UTC, ceydae commented on src/components/CSelect/index.tsx
> +  isCloseModal?: boolean;
rename to isModalClose

2024-08-30 11:54 UTC, ceydae commented on src/components/CSelect/selectCustomStyles.ts
> +  ItemsSelectedLength: number,
selectedItemsLength

Why is the first letter capital?

2024-09-05 21:33 UTC, merged