3 charts
luanlabs/wagent-interface pull request #5
Opened 2024-06-17 16:55 UTC by dousdogukan

### Description

implement **CBarChart**
implement **CPieChart**
implement **CCoinLabel**
implement **CStatusCard**

### Checklist

- [ ] Tested changes locally.
- [ ] Ensured code follows project standards.
- [ ] Updated documentation.
- [ ] Added necessary tests.

### Additional Notes

Charts are not displayed properly on large screens.

for #3

2024-06-19 21:10 UTC, ruveyda-kisla commented
Chart in dashboard takes too much space that the Aside menu wouldn't open properly.

2024-06-21 12:36 UTC, ceydae requested changes
1. We do not need any hovers for the donut chart.
2. We need the percentages beside the donut chart (sorted by the largest percentage being on the first spot)
3. Try to use a thin font for percentages in the bar chart
4. Rename the Pie chart to Donut chart in the whole project.
5. The hover of the BarChart should show a price. So, use $ befoe the price and the style is bad.

2024-06-21 12:36 UTC, ceydae commented on src/assets/Arrow.tsx
> +      stroke-linejoin="round"
invalid props, use camelCase like props to avoid any console.log errors

2024-06-21 12:36 UTC, ceydae commented on src/components/CCoinLabel/coinStyle.ts
> +      };
remove the function and the switch case, just export an object. Like so:

```
{
  eth: {},
  xlm: {}
```

2024-06-21 12:36 UTC, ceydae commented on src/components/CCoinLabel/coinStyle.ts
rename to tokensStyles

2024-06-21 12:36 UTC, ceydae commented on src/components/CCoinLabel/index.tsx
> +const CCoinLabel = ({ name, logo }: CCoinLabelProps) => {
create another variable here caled `tokenSymbol` which is `name.toLowerCase()`

2024-06-21 12:36 UTC, ceydae commented on src/components/CCoinLabel/index.tsx
> +const CCoinLabel = ({ name, logo }: CCoinLabelProps) => {
Do not use the work Coin, Use the work token

2024-06-21 12:36 UTC, ceydae commented on src/components/CCoinLabel/index.tsx
> +const CCoinLabel = ({ name, logo }: CCoinLabelProps) => {
Change props to symbol, logo

2024-06-21 12:36 UTC, ceydae commented on src/components/CLabel/index.tsx
> +        )} */}
remove the unused comments

2024-06-21 12:36 UTC, ceydae commented on src/components/CStatusCard/index.tsx
> +  };
move the function to outside the component. To a separate file beside this file

2024-06-21 12:36 UTC, ceydae commented on src/components/CStatusCard/index.tsx
> +                %{new BN(percentage).abs().toFixed()}
Do not do any calculations in JSX, put them in variables above the return statement.

2024-06-21 12:36 UTC, ceydae commented on src/components/Charts/CBarChart/customAxisTick.tsx
> +  return (
add a blank line here

2024-06-21 12:36 UTC, ceydae commented on src/components/Charts/CBarChart/customAxisTick.tsx
If it's a component, it should start with a capital letter (both file and function name)

2024-06-21 12:36 UTC, ceydae commented on src/components/Charts/CBarChart/customLabel.tsx
If it's a component, it should start with a capital letter (both file and function name)

2024-06-21 12:36 UTC, ceydae commented on src/components/Charts/CBarChart/customLabel.tsx
> +    return (
add a blank line here.

2024-06-21 12:36 UTC, ceydae commented on src/components/Charts/CPieChart/customLegend.tsx
If it's a component, it should start with a capital letter (both file and function name)

2024-06-21 12:36 UTC, ceydae commented on src/components/Charts/CPieChart/customLegend.tsx
> +const customLegend = (props: any) => {
do not use `any` type for props

2024-06-21 12:36 UTC, ceydae commented on src/components/Charts/CPieChart/customLegend.tsx
> +    <div className="">
remove the unnecessary className

2024-06-21 12:36 UTC, ceydae commented on src/components/Charts/CPieChart/index.tsx
> +
remove the blank line

2024-06-21 12:36 UTC, ceydae commented on src/containers/CPieChartContainer/index.tsx
> +  const [chartData, setChartData] = useState<PieChartDataType[]>();
Give this state a default value `[]`

2024-06-21 12:36 UTC, ceydae commented on src/containers/CPieChartContainer/index.tsx
> +            {chartData?.map((data) => (
remove the ?

2024-06-25 07:01 UTC, ceydae requested changes
Use percentages like so (no space between the number and the % symbol and the symbol is on the right side of the number):

19%

2024-06-25 20:31 UTC, ruveyda-kisla approved these changes

2024-06-29 06:53 UTC, ceydae commented
Rename custom.. components to Custom

2024-06-29 06:54 UTC, ceydae commented
Resolve conflicts with `master`

2024-06-29 12:39 UTC, merged