53 acceptable payment methods in setting
luanlabs/wagent-interface pull request #54
Opened 2024-08-07 11:29 UTC by dousdogukan

### Description

completed acceptable payment methods.

### Checklist

- [ ] Tested changes locally.
- [ ] Ensured code follows project standards.
- [ ] Updated documentation.
- [ ] Added necessary tests.

### Additional Notes

for #53

2024-08-10 23:50 UTC, ceydae requested changes

2024-08-10 23:50 UTC, ceydae commented on src/containers/SettingsContainer/index.tsx
> +  const [isCheckedVesting, setIsCheckedVesting] = useState(false);
isStreamChecked
isVestingChecked

2024-08-10 23:50 UTC, ceydae commented on src/containers/SettingsContainer/index.tsx
> +  const vestingStyle = isCheckedVesting ? '#101828' : '#98A2B3';
use `vertingColor` or something similar

2024-08-14 12:01 UTC, ruveyda-kisla approved these changes

2024-08-25 15:41 UTC, ceydae approved these changes

2024-08-25 15:42 UTC, merged