feat: add Sign out to settings
luanlabs/wagent-interface pull request #57
Opened 2024-08-09 16:10 UTC by ruveyda-kisla

### Description
issue: #56

Added Sign out option to Settings

### Checklist

- [x] Tested changes locally.
- [x] Ensured code follows project standards.
- [x] Updated documentation.
- [x] Added necessary tests.

2024-08-09 16:20 UTC, dousdogukan approved these changes

2024-08-10 23:48 UTC, ceydae requested changes

2024-08-10 23:48 UTC, ceydae commented on src/containers/SettingsContainer/index.tsx
>      console.log(e.target.name);
remove console.logs

2024-08-10 23:48 UTC, ceydae commented on src/containers/SettingsContainer/index.tsx
> +    }
use localStorage.clear and sessionStorage.clear instead of this

2024-08-21 22:17 UTC, ceydae approved these changes

2024-08-21 22:17 UTC, merged