Feat push notification
luanlabs/wagent-interface pull request #59
Opened 2024-08-20 17:15 UTC by ruveyda-kisla

### Description

- add pwa support
- add firebase and notification example

### Checklist

- [x] Tested changes locally.
- [x] Ensured code follows project standards.
- [x] Updated documentation.
- [x] Added necessary tests.

2024-08-21 22:34 UTC, ceydae requested changes

2024-08-21 22:34 UTC, ceydae commented on public/firebase-messaging-sw.js
> +  clients.matchAll({ type: 'window' }).then(function (windowClients) {
console.log clients and see what that is

2024-08-21 22:34 UTC, ceydae commented on public/firebase-messaging-sw.js
> +    const iconUrl = './images/wagentLogo.svg';
change iconUrl to an absolute url

2024-08-21 22:34 UTC, ceydae commented on public/sw.js
is this file needed?

2024-08-21 22:34 UTC, ceydae commented on public/sw.js.map
is this needed?

2024-08-21 22:34 UTC, ceydae commented on src/app/layout.tsx
is this line needed?

2024-08-21 22:34 UTC, ceydae commented on src/app/page.tsx
remove test component

2024-08-21 22:34 UTC, ceydae commented on src/containers/Test/index.tsx
> +    requestNotificationPermission();
Call this in a file that if the page loads, it calls this function. 

I don't know what is the appropriate file is in Next 14 though

2024-08-21 22:34 UTC, ceydae commented on src/services/firebase.ts
> +      console.log('No registration token available. Request permission to generate one.');
change the `getToken` to something like `sendClientToken` and send the token to the back-end to store for future use.

2024-08-24 21:08 UTC, ruveyda-kisla commented on src/app/layout.tsx
if you mean manifest meta tag 
Yes

2024-08-25 15:41 UTC, ceydae approved these changes

2024-08-25 15:41 UTC, merged