6 product page
luanlabs/wagent-interface pull request #7
Opened 2024-06-19 21:51 UTC by dousdogukan

### Description

implement **Products page** 
implement **CMethod** and **CIteamCard**

### Checklist

- [ ] Tested changes locally.
- [ ] Ensured code follows project standards.
- [ ] Updated documentation.
- [ ] Added necessary tests.

### Additional Notes

The product modal will be created in the subsequent PRs.
The coin labels will be added after merging the previous PR.
In CItemCard, there are two states: product and transaction.
After merging this PR, the transaction styles will be added to CItemCard.

for #6

2024-06-21 12:52 UTC, ceydae requested changes
`Module not found: Can't resolve 'clsx'`

The app does not run

2024-06-21 12:52 UTC, ceydae commented on src/app/products/page.tsx
> +  );
Move this out of the Proucts component

2024-06-21 12:52 UTC, ceydae commented on src/assets/Stream.tsx
> +  </svg>
invalid props, use camelCase

2024-06-25 07:34 UTC, ceydae requested changes
remove space between # and id

2024-06-25 07:34 UTC, ceydae commented on src/components/CItemCard/index.tsx
This is a wrong way of making a component for both Product and Transaction.

2024-06-25 19:34 UTC, ruveyda-kisla approved these changes

2024-06-29 06:47 UTC, ceydae requested changes

2024-06-29 06:47 UTC, ceydae commented on src/components/CItemCard/index.tsx
> +  method: MethodType;
remove `method` type from props of this component

2024-06-29 12:40 UTC, merged